### ISSUE TITLE
HazelcastContainer is not working with hazercast client

### ISSUE THREAD

**Issue by haider665** [nolequen/hazelcast-testcontainer#1]
I have a hazelcast client config in hazercast-client.yml. I have tried HazelcastContainer but its not working
```
hazelcast-client:
  cluster-name: test
  instance-name: test-service
  network:
    cluster-members:
      - 127.0.0.1
    smart-routing: false
```

TestContainerDemo.java

```
      protected static HazelcastContainer hazelcastContainer = new HazelcastContainer("latest");

    @BeforeAll
    public static void initContainers() {
        hazelcastContainer.start();
    }

    @DynamicPropertySource
    static void registerDynamicProperties(DynamicPropertyRegistry registry) {
        registry.add("hazelcast-client.network.cluster-members", () -> hazelcastContainer.getHost());
    }
```
